services:
    db:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_USER: example
            POSTGRES_PASSWORD: example
            POSTGRES_DB: example
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    etl:
        build: .
        restart: always
        depends_on:
            - db
        command: --conn_str=postgresql://example:example@db:5432/example

volumes:
  pgdata:
